// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Activities: typeof import('./components/Filters/Activities.vue')['default']
    Activity: typeof import('./components/Filters/Activity.vue')['default']
    AsideBar: typeof import('./components/AsideBar/index.vue')['default']
    AsideMenuItem: typeof import('./components/AsideMenus/AsideMenuItem.vue')['default']
    AsideMenus: typeof import('./components/AsideMenus/index.vue')['default']
    Author: typeof import('./components/Author/index.vue')['default']
    ConfirmModal: typeof import('./components/Modal/ConfirmModal.vue')['default']
    CourseCard: typeof import('./components/CourseCard/index.vue')['default']
    CourseContent: typeof import('./components/CourseContent/index.vue')['default']
    CourseLine: typeof import('./components/CourseLine/index.vue')['default']
    CourseSale: typeof import('./components/CourseSale/index.vue')['default']
    CourseStatistics: typeof import('./components/CourseStatistics/index.vue')['default']
    Episode: typeof import('./components/Episode/index.vue')['default']
    Filters: typeof import('./components/Filters/index.vue')['default']
    FiveStar: typeof import('./components/FiveStar/index.vue')['default']
    Fold: typeof import('./components/Fold/index.vue')['default']
    Layout: typeof import('./components/Layout/index.vue')['default']
    MainLayout: typeof import('./components/MainLayout/index.vue')['default']
    Mask: typeof import('./components/Mask/index.vue')['default']
    Message: typeof import('./components/Message/index.vue')['default']
    MessageContainer: typeof import('./components/Message/MessageContainer.vue')['default']
    Modal: typeof import('./components/Modal/index.vue')['default']
    PageHeader: typeof import('./components/PageHeader/index.vue')['default']
    PageSwiper: typeof import('./components/PageSwiper/index.vue')['default']
    ProfileLayout: typeof import('./components/ProfileLayout/index.vue')['default']
    Rectangle: typeof import('./components/Rectangle/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTitle: typeof import('./components/SearchTitle/index.vue')['default']
    StarRadio: typeof import('./components/StarRadio/index.vue')['default']
    Tag: typeof import('./components/Tag/index.vue')['default']
    Textarea: typeof import('./components/Textarea/index.vue')['default']
    TitleCheckbox: typeof import('./components/TitleCheckbox/index.vue')['default']
    Upload: typeof import('./components/Upload/index.vue')['default']
    VButton: typeof import('./components/VButton/index.vue')['default']
    VForm: typeof import('./components/VForm/index.vue')['default']
    VFormItem: typeof import('./components/VForm/VFormItem.vue')['default']
    VInput: typeof import('./components/VInput/index.vue')['default']
    VMask: typeof import('./components/VMask/index.vue')['default']
    VTextarea: typeof import('./components/VTextarea/index.vue')['default']
  }
}
